* Set TTL for packages
  sudo iptables -t mangle -A POSTROUTING -o usb0 -j TTL --ttl-set 65
* Setup NAT
  sudo iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
* Git check repo whitespace
  git commit --allow-empty
  # Always create a merge commit
  git merge --no-ff
* Good example C comments
/**
 * Copies the default config to startup.
 * Reads the default config file/partition,
 * stripping the headers and validating the md5sum,
 * and writes it to the startup config.
 * @param  msg  - destanation masage
 * @retval 0 if successful.
 * @retval 1 if the default config does not exist.
 * @retval other in case of error.
 */
* Sites for test regular expression
  https://www.debuggex.com/
  https://regexper.com/
* How install java on Linux
  http://www.backtrack-linux.org/wiki/index.php/Java_Install
* Mount disk on rw mode from ro mode
  mount -o remount, rw /
* Emacs. How enable merge conflict resolve mode
  vc-resolve-conflicts
* How show RAM information
  dmidecode -t memory
* How remove attribute
** Install
   yaourt mat mutagen perl-image-exiftool
** Check
   mat -c <file>
** Show metadata
   mat -d <file>
** Delete metadata
   mat -b <file>
* How add fat and ntfs tools
  pacman -S dosfstools ntfsprogs
* How add file system for flash
  pacman -S f2fs-tools
* How change layout on i3
  Create file /etc/X11/xorg.conf.d/00-keyboard.conf and write:
  Section "InputClass"
  	Identifier "system-keyboard"
  	MatchIsKeyboard "on"
  	Option "XkbLayout" "us,ru"
  	Option "XkbVariant" ","
  	Option "XkbOptions" "grp:caps_toggle"
  EndSection
* ASCIIFLOW
  http://nightly.ascii-flow.appspot.com/#Draw
* Service for found photo
  snradar.azurewebsites.net
* Emacs git blame
  M-x vc-annotate
* ARCH. remove all unused packages
  pacman -Rsn $(pacman -Qqdt)
* ARCH. Connect to wifi with NetworkManager
** Show list network devices
   nmcli dev
** Connect to wifi
   nmcli dev wifi connect SSID password PASS
   nmcli dev wifi connect SSID password PASS iface wlan0
   nmcli dev disconnect wlan0
** Turn off wifi
   nmcli r wifi off/on
* How setup WiFi card on promiscuous mode
** Find your phy
   iw phy
** Add new interface
   iw phy phyX interface add mon0 type monitor
   iw dev mon0 del
** With iw
   iw dev wlan0 set type monitor
   iw dev wlan0 set type managed
** Set channel for listen
   iw dev wlan0 set channel *channel*
* Unprivileged power management
  pacman -S polkit
* Run command on every find file
  find -name "name" -execdir command {} \;
* Error with start X server
  Create file /etc/X11/Xwrapper.config and write
  allowed_user=anybody
* Objdump
  objdump -D file
  addr2line -e file -a 0x(addr)
  strip
* Get information about interface
  ethtool eth0
** Setup speed interface
   ethtool -s eth0 speed 100 autoneg off
* Show last installed packed
  expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort
  expac -S -H M '%k\t%n' | sort -h
* LVM
** LVM setup
*** Create physichal volume
    pvcreate /dev/sda1 /dev/sda2
*** Create volume group
    vgcreate name_group /dev/sda1 /dev/sda2
    vgdisplay
*** Create logical volume
    lvcreate -n name_volume -L size name_group
    lvdisplay
    lvextend -L +size /dev/name_group/name_volume
*** Resize FS
    resize2fs /dev/name_group/name_volume

** Crypt setup
*** Encrypt dev
    cryptsetup luksFormat /dev/sda2
*** Open
    cryptsetup open /dev/sda2 name_crypt
*** Edit /etc/default/grub
    cryptdevice=/dev/sda2:name_crypt
* XORG how disable auto sleep
  xset -dpms

  /etc/X11/xorg.conf

Section "ServerLayout"
          Identifier     "Layout0"
          Screen      0  "Screen0"
          InputDevice    "Keyboard0" "CoreKeyboard"
          InputDevice    "Evdev Mouse" "CorePointer"
          Option "BlankTime" "0"
          Option "StandbyTime" "0"
          Option "SuspendTime" "0"
          Option "OffTime" "0"
EndSection
* How manage images
  pacman -S imagemagic
** Conver
   convert image.png image.jpg
** Resize
   convert image.png -resize 200x100 image.png
   -resize 200x100! # Force resize
   -resize 200 # Only height
   -resize x200 # Only weight
** Rotate
   convert image.png -rotate 90 image.png
* GIT. Find remove string
  git log -S <string> path/to/file
