* Difference between folders
  meld
* Set TTL for packages
  sudo iptables -t mangle -A POSTROUTING -o usb0 -j TTL --ttl-set 65
* Setup NAT
  sudo iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
* Git check repo whitespace
  # Show whitespace
  git diff --check
  # Push force and check for change repo
  git push --force-with-lease
  git commit --allow-empty
  # Always create a merge commit
  git merge --no-ff
* Good example C comments
/**
 * Copies the default config to startup.
 * Reads the default config file/partition,
 * stripping the headers and validating the md5sum,
 * and writes it to the startup config.
 * @param  msg  - destanation masage
 * @retval 0 if successful.
 * @retval 1 if the default config does not exist.
 * @retval other in case of error.
 */
* Sites for test regular expression
  https://www.debuggex.com/
  https://regexper.com/
* How install java on Linux
  http://www.backtrack-linux.org/wiki/index.php/Java_Install
* Mount disk on rw mode from ro mode
  mount -o remount, rw /
* Emacs. How enable merge conflict resolve mode
  vc-resolve-conflicts
* Arch Network
** How use ip application
*** setup route
    ip route add default via IP
    ip route del default
    ip route flush dev eth0
*** setup link
    ip link set eth0 up
*** setup static ip
    ip addr add 192.168.1.1/24 brd 192.168.1.255 dev eth0
    ip addr flush dev eth0
*** connect to wifi
    iwlist wlan0 scanning
    ip link set wlan0 up
    iwconfig wlan0 essid SSID
** How use NetworkManager
   systemctl start NetworkManager
*** Connect to wifi
    nmcli dev wifi connect <name> password <pass> iface wlan1
** How use pptp
   pptpsetup --create my_tunnel --server vpn.example.com --username alice --password poor
   pptpsetup --delete my_tunnel
   pon my_tunnel
* How show RAM information
  dmidecode -t memory
* How remove attribute
** Install
   yaourt mat mutagen perl-image-exiftool
** Check
   mat -c <file>
** Show metadata
   mat -d <file>
** Delete metadata
   mat -b <file>
