#!/bin/bash

FIRST_COLOR="#445d67"
SECOND_COLOR="#3b4549"
GOOD_TEXT_COLOR="#eef6eb"
BAD_TEXT_COLOR="#ff0000"

print_good() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "$1" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$GOOD_TEXT_COLOR"
}

print_bad() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "$1" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$BAD_TEXT_COLOR"
}

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

cmp="$(echo "$load > $cpus" | bc -l)"

if [[ $cmp -ne 0 ]]; then
	print_bad $load
else
	print_good $load
fi
echo
