#!/bin/bash

FIRST_COLOR="#6e4555"
SECOND_COLOR="#4e3c43"
TEXT_COLOR="#eef6eb"

print_good() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "$1" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$TEXT_COLOR"
}

print_bad() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "$1" "down" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$TEXT_COLOR"
}

if [[ -z $BLOCK_INSTANCE ]]; then
	print_bad "None"
	echo
	exit 0
fi
IFACE=$BLOCK_INSTANCE

STR=$(ip link show $IFACE 2>/dev/null)

if [[ -z $STR ]]; then
	print_bad $IFACE
	echo
	exit 0
fi

ARR=(${STR// / })
if [[ ${ARR[8]} == 'DOWN' ]]; then
	print_bad $IFACE
else
	IP=($(ip addr show $IFACE | grep '\binet\b' | awk '{print $2}' | cut -d '/' -f 1 | tr '\n' '/' | sed 's/\/$//'))

	print_good $IP
fi
echo
