#!/bin/bash

FIRST_COLOR="#6e4555"
SECOND_COLOR="#4e3c43"
TEXT_COLOR="#eef6eb"

# SSID SIGNAL IP
print_good() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "$1 - $3" "" "$2" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$TEXT_COLOR"
}

print_bad() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "down" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$TEXT_COLOR"
}

if [[ -z $BLOCK_INSTANCE ]]; then
	print_bad
	exit 0
fi
IFACE=$BLOCK_INSTANCE

STR=$(iw dev $IFACE link)
if [[  $STR == 'Not connected.' ]]; then
	print_bad
else
	ARR=(${STR// /})
	SSID=$(echo ${ARR[1]} | cut -d ':' -f 2)
	SIGNAL=$(echo ${ARR[5]} | cut -d ':' -f 2)
	IP=($(ip addr show $IFACE | grep '\binet\b' | awk '{print $2}' | cut -d '/' -f 1))
	print_good $SSID $SIGNAL $IP
fi
