#!/bin/bash

NONE="#2f343f"
BG="#597262"
TEXT="#4d504e"

BAT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)

echo -ne "<span background='$BG' foreground='$NONE'>"
echo -ne "\ue0b8" # Open
echo -ne "</span>"

echo -ne "<span background='$BG' foreground='#000000' font_family='FontAwesome'>"
if [[ $STATUS == "Charging" ]]; then
	echo -ne "\uf0e7 " # Light
fi

if [[ $BAT -gt 75 && $BAT -le 100 ]]; then
	echo -ne "\uf240" # 100
elif [[ $BAT -gt 50 && $BAT -le 75 ]]; then
	echo -ne "\uf241" # 75
elif [[ $BAT -gt 25 && $BAT -le 50 ]]; then
	echo -ne "\uf242" # 50
elif [[ $BAT -gt 10 && $BAT -le 25 ]]; then
	echo -ne "\uf243" # 25
elif [[ $BAT -ge 0 && $BAT -le 10 ]]; then
	echo -ne "\uf244" # 25
fi
echo -ne "</span>"

echo -ne "<span background='$TEXT' foreground='$BG'>"
echo -ne "\ue0b8" # Open
echo -ne "</span>"

echo -ne "<span background='$TEXT' foreground='#eef6eb'>"
echo -n "$BAT%"
echo -ne "</span>"

echo -ne "<span background='$NONE' foreground='$TEXT'>"
echo -ne "\ue0b8" # Close
echo -ne "</span>"
