#!/bin/sh

NONE="#2f343f"
BG="#7fa286"
BG="#597262"
TEXT="#6d726e"
TEXT="#4d504e"

xml_save_print() {
    # Replace all xml bad symbols
    # & -- &amp;
    # < -- &lt;
    # > -- &gt;
    echo -n $@ | sed $'s/&/\\&amp;/g; s/</\\&lt;/g; s/>/\\&gt;/g'
}

print_artist_title() {
    echo -ne "<span background='$BG' foreground='$NONE'>"
    echo -ne "\ue0b8" # Open
    echo -ne "</span>"

    echo -ne "<span background='$BG' foreground='#000000'>"
    echo -ne "\uf886" # Music note
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='$BG'>"
    echo -ne "\ue0b8" # Open
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='#eef6eb'>"
    artist=$(echo $status | grep -Po '(?<=(ARTIST = )).*(?= ALBUMARTIST)')
    title=$(echo $status | grep -Po '(?<=(TITLE = )).*(?= ALBUM)')
    if [[ $artist != "" && $title != "" ]]; then
        xml_save_print "$artist - $title"
    elif [[ $artist != "" ]]; then
        xml_save_print "$artist"
    elif [[ $title != "" ]]; then
        xml_save_print "$title"
    else
        xml_save_print "No tags"
    fi
    echo -ne "</span>"

    echo -ne "<span background='$BG' foreground='$TEXT'>"
    echo -ne "\ue0b8" # Close
    echo -ne "</span>"
}

print_progress() {
    sts=$(echo $status | grep -o -m 1 "^\[.*]")

    echo -ne "<span background='$BG' foreground='#000000'>"
    case $sts in
        "[paused]"*)
            echo -ne "\uf04c" # Pause
            ;;
        "[playing]"*)
            echo -ne "\uf04b" # Play
            ;;
        "[stopped]"*)
            echo -ne "\uf04d" # Stop
            ;;
        *)
            echo -n Error
            ;;
    esac
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='$BG'>"
    echo -ne "\ue0b8" # Open
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='#eef6eb' ><tt><small>"
    progress=$(echo $status | cut -d ' ' -f 3)
    if [[ $progress != "" ]]; then
        echo -n "$progress"
    fi
    echo -ne "</small></tt></span>"

    echo -ne "<span background='$NONE' foreground='$TEXT'>"
    echo -ne "\ue0b8" # Close
    echo -ne "</span>"
}

status=$(timeout 3 qmmp --no-start --status)
if [[ $status != "" ]]; then
    print_artist_title
    print_progress
else
    echo
fi
