#!/bin/bash

NONE="#2f343f"
BG="#445d67"
TEXT="#3b4549"

print() {
	echo -ne "<span background='$BG' foreground='$NONE'>"
	echo -ne "\ue0b8" # Open
	echo -ne "</span>"

	echo -ne "<span background='$BG' foreground='#000000'>"
	echo -ne "\uf2db" # RAM
	echo -ne "</span>"

	echo -ne "<span background='$TEXT' foreground='$BG'>"
	echo -ne "\ue0b8" # Open
	echo -ne "</span>"

	echo -ne "<span background='$TEXT' foreground='#eef6eb'>"
	echo -ne "$1G"
	echo -ne "</span>"

	echo -ne "<span background='$NONE' foreground='$TEXT'>"
	echo -ne "\ue0b8" # Close
	echo -ne "</span>"
}

MEM_FREE=$(cat /proc/meminfo | grep MemFree | awk '{print $2}')
MEM_BUFFERS=$(cat /proc/meminfo | grep Buffers | awk '{print $2}')
MEM_CACHED=$(cat /proc/meminfo | grep '^Cached' | awk '{print $2}')
print $(echo "scale=1; ($MEM_FREE + $MEM_BUFFERS + $MEM_CACHED)/1024/1024" | bc)
