#!/bin/bash

NONE="#2f343f"
BG="#8b8367"
TEXT="#626059"

echo -ne "<span background='$BG' foreground='$NONE'>"
echo -ne "\ue0b8" # Open
echo -ne "</span>"

echo -ne "<span background='$BG' foreground='#000000'>"
echo -ne "\ufac9" # Lang
echo -ne "</span>"

echo -ne "<span background='$TEXT' foreground='$BG'>"
echo -ne "\ue0b8" # Open
echo -ne "</span>"

echo -ne "<span background='$TEXT' foreground='#eef6eb'>"
VAL=$(xset -q | grep LED | cut -d ':' -f 4 | cut -c 7-9)
case $VAL in
    "000")
        echo -n Eng
        ;;
    "100")
        echo -n Rus
        ;;
    *)
        echo -n $VAL
        ;;
esac
echo -ne "</span>"

echo -ne "<span background='$NONE' foreground='$TEXT'>"
echo -ne "\ue0b8" # Close
echo -ne "</span>"
