#!/bin/bash

NONE="#2f343f"
BG="#6e4555"
TEXT="#4e3c43"

print_good() {
	echo -ne "<span background='$BG' foreground='$NONE'>"
	echo -ne "\ue0b8" # Open
	echo -ne "</span>"

	echo -ne "<span background='$BG' foreground='#000000'>"
	echo -ne "\uf700" # Ethernet good
	echo -ne "</span>"

	echo -ne "<span background='$TEXT' foreground='$BG'>"
	echo -ne "\ue0b8" # Open
	echo -ne "</span>"

	echo -ne "<span background='$TEXT' foreground='#eef6eb'>"
	echo -ne "$1"
	echo -ne "</span>"

	echo -ne "<span background='$NONE' foreground='$TEXT'>"
	echo -ne "\ue0b8" # Close
	echo -ne "</span>"
}

print_bad() {
	echo -ne "<span background='$BG' foreground='$NONE'>"
	echo -ne "\ue0b8" # Open
	echo -ne "</span>"

	echo -ne "<span background='$BG' foreground='#000000'>"
	echo -ne "\uf701" # Ethernet bad
	echo -ne "</span>"

	echo -ne "<span background='$TEXT' foreground='$BG'>"
	echo -ne "\ue0b8" # Open
	echo -ne "</span>"

	echo -ne "<span background='$TEXT' foreground='#eef6eb'>"
	echo -ne "down"
	echo -ne "</span>"

	echo -ne "<span background='$NONE' foreground='$TEXT'>"
	echo -ne "\ue0b8" # Close
	echo -ne "</span>"
}

if [[ -z $BLOCK_INSTANCE ]]; then
	print_bad
	exit 0
fi
IFACE=$BLOCK_INSTANCE

STR=$(ip link show $IFACE 2>/dev/null)

if [[ -z $STR ]]; then
	print_bad
	exit 0
fi

ARR=(${STR// / })
if [[  ${ARR[8]} == 'DOWN' ]]; then
	print_bad
else
	STR=$(ifconfig $IFACE)
	ARR=(${STR// / })
	IP=${ARR[5]}

	print_good $IP
fi
