#!/bin/sh

NONE="#2f343f"
BG="#7fa286"
BG="#597262"
TEXT="#6d726e"
TEXT="#4d504e"

xml_save_print() {
    # Replace all xml bad symbols
    # & -- &amp;
    # < -- &lt;
    # > -- &gt;
    echo -n $@ | sed $'s/&/\\&amp;/g; s/</\\&lt;/g; s/>/\\&gt;/g'
}

print_artist_title() {
    echo -ne "<span background='$BG' foreground='$NONE'>"
    echo -ne "\ue0b8" # Open
    echo -ne "</span>"

    echo -ne "<span background='$BG' foreground='#000000'>"
    echo -ne "\uf886" # Music note
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='$BG'>"
    echo -ne "\ue0b8" # Open
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='#eef6eb'>"
    state=$(ncmpcpp --current-song="{%a - %t}|{%t}|{%f}" 2>/dev/null | cut -c 1-$LEN)
    xml_save_print $state
    echo -ne "</span>"

    echo -ne "<span background='$BG' foreground='$TEXT'>"
    echo -ne "\ue0b8" # Close
    echo -ne "</span>"
}

print_progress() {
    echo -ne "<span background='$BG' foreground='#000000'>"
    case ${status[1]} in
        "[paused]"*)
            echo -ne "\uf04c" # Pause
            ;;
        "[playing]"*)
            echo -ne "\uf04b" # Play
            ;;
        *)
            echo -ne "\uf04d" # Stop
            ;;
    esac
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='$BG'>"
    echo -ne "\ue0b8" # Open
    echo -ne "</span>"

    echo -ne "<span background='$TEXT' foreground='#eef6eb' ><tt><small>"
    progress=$(echo ${status[1]} | awk '{print $3}')
    if [[ $progress != "" ]]; then
        echo -n "$progress"
    else
        echo -n " -/- "
    fi
    echo -ne "</small></tt></span>"

    echo -ne "<span background='$NONE' foreground='$TEXT'>"
    echo -ne "\ue0b8" # Close
    echo -ne "</span>"
}

LEN=70

IFS=$'\n' status=($(mpc status))
if [[ $status != "" ]]; then
    print_artist_title
    print_progress
else
    echo
fi
