#!/bin/bash

FIRST_COLOR="#445d67"
SECOND_COLOR="#3b4549"
TEXT_COLOR="#eef6eb"

MEM_FREE=$(cat /proc/meminfo | grep MemFree | awk '{print $2}')
MEM_BUFFERS=$(cat /proc/meminfo | grep Buffers | awk '{print $2}')
MEM_CACHED=$(cat /proc/meminfo | grep '^Cached' | awk '{print $2}')
VAL=$(echo "scale=1; ($MEM_FREE + $MEM_BUFFERS + $MEM_CACHED)/1024/1024" | bc)

$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "$VAL" "$FIRST_COLOR" \
	"$SECOND_COLOR" "$TEXT_COLOR"

echo
