#!/bin/bash

FIRST_COLOR="#597262"
SECOND_COLOR="#4d504e"
TEXT_COLOR="#eef6eb"

if [[ `pamixer --get-mute` == "true" ]]; then
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "MUTE" \
		"$FIRST_COLOR" "$SECOND_COLOR" "$TEXT_COLOR"
else
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "`pamixer --get-volume`%"\
		"$FIRST_COLOR" "$SECOND_COLOR" "$TEXT_COLOR"
fi
echo
