#!/bin/bash

FIRST_COLOR="#445d67"
SECOND_COLOR="#3b4549"
GOOD_TEXT_COLOR="#eef6eb"
BAD_TEXT_COLOR="#ff0000"

print_good() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "$1" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$GOOD_TEXT_COLOR"
}

print_bad() {
	$HOME/.my_scripts/.data/binary/bracet/bin/bracet "" "$1" "$FIRST_COLOR" \
		"$SECOND_COLOR" "$BAD_TEXT_COLOR"
}

AVAILABLE=$(df -h -P -l $HOME | awk 'NR==2 {print $4}')
USED=$(df -h -P -l $HOME | awk 'NR==2 {print $5}' | cut -d '%' -f 1)

if [[ $USED -ge 90 ]]; then
    print_bad $AVAILABLE
else
    print_good $AVAILABLE
fi
echo
