#! /bin/bash
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
DESC="Logging on and off PC"
NAME=time_logger
SCRIPTNAME=/etc/init.d/$NAME
FILE=~/Desktop/time.log

#
# Function that starts the daemon/service
#

print_month() {
    echo >> $FILE;
    echo >> $FILE;
    month="--------------------"`date +"%B"`"--------------------";
    echo $month >> $FILE;
}

do_start()
{
    last_date=`cat $FILE | grep '> ' | tail -1`;
    if [[ -z $last_date ]]; then
        print_month
    else
        last_month=`echo $last_date | cut -d ' ' -f 3`;
        cur_month=`date +"%h"`;
        if [[ $last_month != $cur_month ]]; then
            print_month
        fi
    fi
    echo -n "> " >> $FILE
    date >> $FILE
}

#
# Function that stops the daemon/service
#
do_stop()
{
    echo -n "< " >> $FILE
    date >> $FILE
    uptime -p >> $FILE
    echo "----------------------------------------------------" >> $FILE
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

:
